const logos = [
    { name: "Aryaman Kalpvruksh", image: "/Images/ClientsLogos/AryamanKalpvruksh.png", id: 1 },
    { name: "Ganesha 48", image: "/Images/ClientsLogos/Ganesha48.png", id: 2 },
    { name: "Samruddh", image: "/Images/ClientsLogos/samruddh.png", id: 3 },
    { name: "Nest", image: "/Images/ClientsLogos/Nest.png", id: 4 },
    { name: "Alulyam", image: "/Images/ClientsLogos/Alulyam.png", id: 5 },
    { name: "Grand City", image: "/Images/ClientsLogos/GrandCity.png", id: 6 },
    { name: "Solitaire", image: "/Images/ClientsLogos/Solitaire.png", id: 7 },
    { name: "Ar Buda Center", image: "/Images/ClientsLogos/ArBudaCenter.png", id: 8 },
    { name: "Shree Hari", image: "/Images/ClientsLogos/ShreeHari.png", id: 9 },
    { name: "Shrimad Glory", image: "/Images/ClientsLogos/ShrimadGlory.png", id: 10 },
    { name: "TNTC", image: "/Images/ClientsLogos/TNTC.png", id: 11 },
    { name: "Laxmi Skycity", image: "/Images/ClientsLogos/LaxmiSkycity.png", id: 12 },
    { name: "The 1st", image: "/Images/ClientsLogos/The1st.png", id: 13 },
    { name: "Prathana Group", image: "/Images/ClientsLogos/PrathanaGroup.png", id: 14 },
    { name: "Saral BuildCon", image: "/Images/ClientsLogos/SaralBuildCon.png", id: 15 },
    { name: "Kalash Group", image: "/Images/ClientsLogos/Kalashgroup.png", id: 16 },
    { name: "Mars Arise", image: "/Images/ClientsLogos/MarsArise.png", id: 17 },
    { name: "DHS Orbit", image: "/Images/ClientsLogos/DHSOrbit.png", id: 18 },
    { name: "Pushkar Industrial Hub", image: "/Images/ClientsLogos/PushkarIndstrialHub.png", id: 19 },
    { name: "Pushkar Luxuria", image: "/Images/ClientsLogos/PushkarLuxuria.png", id: 20 },
    { name: "Pushkar Gold", image: "/Images/ClientsLogos/PushkarGold.png", id: 21 },
    { name: "Shreem Avdhesh", image: "/Images/ClientsLogos/ShreemAvdhesh.png", id: 22 },
    { name: "Shreema Luxuria", image: "/Images/ClientsLogos/ShreemaLuxuria.png", id: 23 },
    { name: "Shreem Maxima", image: "/Images/ClientsLogos/ShreemMaxima.png", id: 24 },
    { name: "Nirgun Trust", image: "/Images/ClientsLogos/NirgunTrust.png", id: 25 },
    { name: "Amara", image: "/Images/ClientsLogos/Amara.png", id: 26 },
    { name: "Swastik Rise", image: "/Images/ClientsLogos/SwastikRise.png", id: 27 },
    { name: "Proxima", image: "/Images/ClientsLogos/Proxima.png", id: 28 },
    { name: "Shrimay Pulence", image: "/Images/ClientsLogos/ShrimayPulence.png", id: 29 },
    { name: "Happy Group", image: "/Images/ClientsLogos/Happygroup.png", id: 30 },
    { name: "Shivana", image: "/Images/ClientsLogos/Shivana.png", id: 31 },
    { name: "Earth Eleanor", image: "/Images/ClientsLogos/EarthEleanor.png", id: 32 },
    { name: "Good Earth", image: "/Images/ClientsLogos/GoodEarth.png", id: 33 },
    { name: "Regalia", image: "/Images/ClientsLogos/Regalia.png", id: 34 },
    { name: "Dev Life Spaces", image: "/Images/ClientsLogos/DevLifeSpaces.png", id: 35 },
    { name: "Praharsh", image: "/Images/ClientsLogos/Praharsh.png", id: 36 },
    { name: "VR Buildcon", image: "/Images/ClientsLogos/VrBuildcon.png", id: 37 },
    { name: "TGS", image: "/Images/ClientsLogos/TGS.png", id: 38 },
    { name: "Oryn Group", image: "/Images/ClientsLogos/OrynGroup.png", id: 39 },
    { name: "Swarnim Shrushti", image: "/Images/ClientsLogos/SwarnimShrushti.png", id: 40 },
    { name: "21 Fly Fot", image: "/Images/ClientsLogos/21FlyFot.png", id: 41 },
    { name: "Antilia One", image: "/Images/ClientsLogos/AntiliaOne.png", id: 42 },
    { name: "Ekta Developers", image: "/Images/ClientsLogos/EktaDevelopers.png", id: 43 },
    { name: "Aksth Elegance", image: "/Images/ClientsLogos/AkshthElegance.png", id: 44 },
    { name: "The Orion", image: "/Images/ClientsLogos/TheOrion.png", id: 45 },
    { name: "Shivanta", image: "/Images/ClientsLogos/Shivanta.png", id: 46 },
    { name: "Elevate", image: "/Images/ClientsLogos/Elevate.png", id: 47 },
    { name: "D&C Developers", image: "/Images/ClientsLogos/D&CDevelopers.png", id: 48 },
    { name: "Aditya Altuss", image: "/Images/ClientsLogos/AdityaAltuss.png", id: 49 },
    { name: "Ananya Allium", image: "/Images/ClientsLogos/AnanyaAllium.png", id: 50 },
    { name: "Sakar Group", image: "/Images/ClientsLogos/Sakargroup.png", id: 51 },
    { name: "Shashwat Group", image: "/Images/ClientsLogos/Shashwatgroup.png", id: 52 },
    { name: "Shashvat", image: "/Images/ClientsLogos/Shashvat.png", id: 53 },
    { name: "Atharv Landmark", image: "/Images/ClientsLogos/AtharvLandmark.png", id: 54 },
    { name: "Shine Swasti", image: "/Images/ClientsLogos/ShineSwasti.png", id: 55 },
    { name: "Dharti Saket", image: "/Images/ClientsLogos/DhartiSaket.png", id: 56 },
    { name: "Pravish", image: "/Images/ClientsLogos/pravish.png", id: 57 },
    { name: "Laxmi Developers", image: "/Images/ClientsLogos/LaxmiDevelopers.png", id: 58 },
    { name: "Elite", image: "/Images/ClientsLogos/Elite.png", id: 59 },
    { name: "Om Elegance", image: "/Images/ClientsLogos/OmElegance.png", id: 60 },
    { name: "Shivalik Sky", image: "/Images/ClientsLogos/ShivalikSky.png", id: 61 },
    { name: "R&R Group", image: "/Images/ClientsLogos/RandRGroup.png", id: 62 },
    { name: "Vinayak", image: "/Images/ClientsLogos/Vinayak.png", id: 63 },
    { name: "Verdana", image: "/Images/ClientsLogos/Verdana.png", id: 64 },
    { name: "Imperial Sky", image: "/Images/ClientsLogos/ImperialSky.png", id: 65 },
    { name: "Ayanam Happiness", image: "/Images/ClientsLogos/AyanamHappiness.png", id: 66 },
    { name: "Sarthak Pulse", image: "/Images/ClientsLogos/SarthakPulse.png", id: 67 },
    { name: "Origin Group", image: "/Images/ClientsLogos/origingroup.png", id: 68 },
    { name: "The Address", image: "/Images/ClientsLogos/TheAdress.png", id: 69 },
    { name: "Love Kuch Villa", image: "/Images/ClientsLogos/LoveKuchVilla.png", id: 70 },
    { name: "Royal Revanta 3", image: "/Images/ClientsLogos/RoyalRevanta3.png", id: 71 },
    { name: "Vision Creative Group", image: "/Images/ClientsLogos/VisionCreativeGroup.png", id: 72 },
    { name: "Sattva", image: "/Images/ClientsLogos/Sattva.png", id: 73 },
    { name: "Aditya Group", image: "/Images/ClientsLogos/AdityaGroup.png", id: 74 },
    { name: "Swami Narayn Group", image: "/Images/ClientsLogos/SwamiNaraynGroup.png", id: 75 },
    { name: "Skydeck 78", image: "/Images/ClientsLogos/Skydeck78.png", id: 76 },
    { name: "Samdev Amara", image: "/Images/ClientsLogos/SamdevAmara.png", id: 77 },
    { name: "Safal Bliss", image: "/Images/ClientsLogos/SafalBlisss.png", id: 78 },
    { name: "Shyam", image: "/Images/ClientsLogos/Shyam.png", id: 79 },
    { name: "Sunwoods", image: "/Images/ClientsLogos/Sunwoods.png", id: 80 },
    { name: "Shypram", image: "/Images/ClientsLogos/Shypram.png", id: 81 },
    { name: "Sahashya", image: "/Images/ClientsLogos/Sahashya.png", id: 82 },
    { name: "Soham Group", image: "/Images/ClientsLogos/Sohamgroup.png", id: 83 },
    { name: "Swara Building Harmony", image: "/Images/ClientsLogos/SwaraBuildingHarmony.png", id: 84 },
    { name: "Sharanya", image: "/Images/ClientsLogos/Sharanya.png", id: 85 },
    { name: "Times Square Arcade Group", image: "/Images/ClientsLogos/TimesSquareArcadeGroup.png", id: 86 },
    { name: "Harmony Harikesh", image: "/Images/ClientsLogos/HarmonyHarikesh.png", id: 87 },
    { name: "Binori", image: "/Images/ClientsLogos/BinoriLogo.png", id: 88 },
    { name: "Money Plant Junction", image: "/Images/ClientsLogos/MoneyPlantJunction.png", id: 89 },
    { name: "Maruti", image: "/Images/ClientsLogos/Maruti.png", id: 90 },
    { name: "BR Enterprises", image: "/Images/ClientsLogos/BREnterprices.png", id: 91 },
    { name: "Sparsh Villa", image: "/Images/ClientsLogos/SparshVilla.png", id: 92 },
    { name: "Durga Developer", image: "/Images/ClientsLogos/DurgaDeveloper.png", id: 93 },
    { name: "SWC SkyLight", image: "/Images/ClientsLogos/SWCSkyLight.png", id: 94 },
    { name: "Shivanta Group", image: "/Images/ClientsLogos/ShivantaGroup.png", id: 95 },
    { name: "VR Group", image: "/Images/ClientsLogos/VRGroup.png", id: 96 },
    { name: "Shilp Group", image: "/Images/ClientsLogos/Shilpgroup.png", id: 97 },
    { name: "Kasper Genesis", image: "/Images/ClientsLogos/KasperGenesis.png", id: 98 },
    { name: "Sundaram Group", image: "/Images/ClientsLogos/Sundaramgroup.png", id: 99 }
];
export default logos;
